CREATE DATABASE LEAVEMANAGMENT;
USE LEAVEMANAGMENT;
CREATE TABLE LOGIN(
 ID INT  PRIMARY KEY AUTO_INCREMENT NOT NULL,
 EMP_ID INT ,
 EMAIL VARCHAR(100) UNIQUE NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
 FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);

CREATE TABLE EMPLOYEES(
	EMP_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMP_NAME VARCHAR(100) NOT NULL,
    EMP_EMAIL VARCHAR(100) NOT NULL,
    DOB DATE NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    MANAGER_ID INT,
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMP_ID)
);


CREATE TABLE LEAVES (
    LEAVE_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMP_ID INT NOT NULL,
    LEAVE_TYPE ENUM('SICK', 'PTO', 'OTHER') NOT NULL,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE NOT NULL,
    REASON TEXT,
    MANAGER_ID INT,
    STATUS ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
   
);
select * from login;
select * from employees;
select * from leaves;







INSERT INTO LOGIN (EMAIL, PASSWORD) VALUES ('girisha@wavemaker.com', '123');
INSERT INTO LOGIN (EMAIL, PASSWORD) VALUES ('megha@wavemaker.com', '123');
INSERT INTO LOGIN (EMAIL, PASSWORD) VALUES ('meghana@wavemaker.com', '123');
INSERT INTO LOGIN (EMAIL, PASSWORD) VALUES ('kalyani@wavemaker.com', '123');
INSERT INTO LOGIN (EMAIL, PASSWORD) VALUES ('usha@wavemaker.com', '123');
INSERT INTO LOGIN (EMAIL, PASSWORD) VALUES ('leela@wavemaker.com', '123');
INSERT INTO LOGIN (EMAIL, PASSWORD) VALUES ('suma@wavemaker.com', '123');
INSERT INTO LOGIN (EMAIL, PASSWORD) VALUES ('lopa@wavemaker.com', '123');
INSERT INTO LOGIN (EMAIL, PASSWORD) VALUES ('roopa@wavemaker.com', '123');


SELECT * FROM LEAVES;

drop database leavemanagment;

-- CREATE TABLE LeaveSummary (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     EMP_ID INT,
--     LEAVE_TYPE ENUM('SICK','PTO','CASUAL LEAVE'),
--     AVAILABLE INT NOT NULL,
--     USED INT NOT NULL,
--     REMAINING INT NOT NULL,
--     FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
-- );
describe table Leaves;
insert into employees ( LOGIN_ID,EMP_NAME, EMP_EMAIL,DOB,PHONE_NUMBER)values
						(1,'Girisha','girisha@wavemaker.com','2022-07-04','9349875646') ;
insert into employees ( LOGIN_ID,EMP_NAME, EMP_EMAIL,DOB,PHONE_NUMBER)values
						(2,'Meghana','meghana@wavemaker.com','20-09-2024','9349875647') ;
	

SELECT * FROM EMPLOYEES;










SELECT 
    e.EMP_NAME,
    e.EMP_EMAIL,
    l.LEAVE_TYPE,
    l.FROM_DATE,
    l.TO_DATE,
    l.REASON,
    l.STATUS
FROM 
    EMPLOYEES e
JOIN 
    LEAVES l ON e.EMP_ID = l.EMP_ID;
