CREATE DATABASE LEAVE_MANAGEMENT;
USE LEAVE_MANAGEMENT;

DROP TABLE IF EXISTS LEAVES;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS LOGIN;

-- Recreate tables
CREATE TABLE LOGIN (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(50)
);
select * from login;
select * from employees;
CREATE TABLE EMPLOYEES (
    EMP_ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    LOGIN_ID INT,
    empName VARCHAR(255) NOT NULL,
    empMail VARCHAR(255) UNIQUE,
    dob DATE,
    phoneNumber INT,
    managerId INT,
    FOREIGN KEY (LOGIN_ID) REFERENCES LOGIN(ID),
    FOREIGN KEY (managerId) REFERENCES EMPLOYEES(EMP_ID)
);

CREATE TABLE LEAVES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMP_ID INT,
    LEAVE_TYPE ENUM('SICK','PTO','MATERNITY','PATERNITY'),
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE,
    REASON TEXT,
    managerId INT,
    STATUS ENUM('ACCEPTED','REJECTED','PENDING','UNPAID') NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID),
    FOREIGN KEY (managerId) REFERENCES EMPLOYEES(EMP_ID)
);
